### ISSUE TITLE
playback stutter

### ISSUE THREAD

**Issue by farhanito** [HitcherUK/skin.ftv#10]
i really like this skin, sadly I'm having really bad stuttering during video playback.

I'm using latest CoreELEC leia. 
log: http://ix.io/1oPh

thanks

**Comment by HitcherUK** [comment]
Are you sure you're not using a modded version of my skin because it doesn't have these includes - DefaultBackground, TopBar, and BottomBar?

**Comment by farhanito** [comment]
It was installed from official Kodi repo.

I'll try installing directly from GitHub. Thanks

**Comment by HitcherUK** [comment]
Don't see how this can be a skin issue so closing.
