### ISSUE TITLE
Version 4.10 an the Skin-Shortcuts-Script !

### ISSUE THREAD

**Issue by maryo1980** [HitcherUK/skin.ftv#11]
Today I installed Kodi 18 RC 3. I did not install Kodi for some time. I was not able to create Custom Shortcuts. Deinstalled it and installed Kodi 17.6 with FTV 3.2. There i noticed that there is an Advice to install the Skin-Shortcuts-Script to make the Shortcuts work. This Advice is MISSING in the 4.10 Version. I Reinstalled Kodi 18 and Version 4.10 of FTV. I looked for that Advice but could not find it anywhere. I installed the Skin-Shortcuts-Script and voila, it was working on KODI 18 aswell with Version 4.10. So if the Advice to install this Script is missing in later versions people might think your Skin is not working because they have no information that they have to install this script in Order to make it work. I recommen to add this Advice in all version where it is missing or  add the Skin-Shortcuts-Script to the dependencies of FTV to avoid this error from ground up. Thank you for the good work i am a great Fan of this Skin.

**Comment by HitcherUK** [comment]
That's not the official repo version you're using but instead a WIP as I'm moving towards doing away with Skin Shortcuts altogether for the next official release.
